#!/bin/bash

#################################################################################################################
#
#       NAME: updateserver
#
#       AUTHOR:  B3nd3r15
#
#       SUPPORT:  None
#
#       DESCRIPTION:  Update Linux Server,enable TCP BBR, and set NTP servers.
#
#       License: GPL-3.0
#       https://github.com/B3nd3r15/linuxscripts/blob/master/LICENSE
#
#################################################################################################################
#
#       ASSUMPTIONS: Script is run manually, target server has access to internet.
#
#       INSTALL LOCATION: put file in /usr/bin then run chmod +x updateserver
#
#################################################################################################################
#
#       Commands:
#           timestamp
#           kernelversion
#           ntpconfig
#           tcpbbr
#           yumupdate
#           aptupdate
#           automatic
#           autoupdate
#
#################################################################################################################
#
#    Version      AUTHOR      DATE          COMMENTS
#                 ------      ----          --------
#  VER 1.0.5      B3nd3r      2019/07/05    fixed echo output verbage.
#  VER 1.0.4      B3nd3r      2019/07/05    added logging to cleanup function and version #.
#  VER 1.0.3      B3nd3r      2019/07/05    updated log typo and version #.
#  VER 1.0.2      B3nd3r      2019/07/05    updated curl command to use curl -j and version #.
#  VER 1.0.1      B3nd3r      2019/07/05    Fixed typo in autoupdate function.
#  VER 1.0.0      B3nd3r      2019/07/05    Added autoupdate function to keep script updated from github master repo.
#  VER 0.9.0      B3nd3r      2019/06/20    Updated aptupdate function - change purge config files command, commented old command for backup.
#  VER 0.8.0      B3nd3r      2019/06/20    Updated run as root command.
#  VER 0.7.0      B3nd3r      2019/06/20    Added space to output of kernelversion function.
#  VER 0.6.0      B3nd3r      2019/06/20    Added commands section,changed filename to updateserver and automatic function to do all the things.
#  VER 0.5.0      B3nd3r      2019/06/20    Added line at the bottom of script to call functions directly from cmd line.
#  VER 0.4.0      B3nd3r      2019/02/27    sent do-release-upgrade to /dev/null and added extra space in output for NTP.
#  VER 0.3.0      B3nd3r      2019/02/25    Created TCPBBR function to configure tcp to use bbr congestion control.
#  VER 0.2.0      B3nd3r      2019/02/18    sent echo commands to /dev/null so it doesn't fill up the screen.
#  VER 0.1.0      B3nd3r      2019/01/23    Initial creation and release.
#
#################################################################################################################


#--------------------------
# Global Variables.
#--------------------------

#-----------------------------------------------
# Script Version for updating.
#-----------------------------------------------
version=1.0.5

#-----------------------------------------------
# Pulls the script name without directory paths.
#-----------------------------------------------
scriptname="$(basename "${0}")"

#---------------------------------
# Run as Root.
#---------------------------------
#if (( EUID != 0 )); then
#        sudo /home/"$USER"/"$scriptname"
#        exit
#fi
if [ "$(id -u)" != "0" ]; then
  exec sudo "$0" "$@" 
fi
#---------------------------------
# Set log Location.
#---------------------------------
LOG_LOCATION=/var/log
exec > >(tee -ai $LOG_LOCATION/"${scriptname}".log )
exec 2>&1
echo ""

#----------------------------------
# Bash Colors.
#----------------------------------
reset="\033[0m"
red="\033[0;31m"          # Red
green="\033[0;32m"        # Green
yellow="\033[0;33m"       # Yellow
blue="\033[0;34m"         # Blue
cyan="\033[0;36m"         # Cyan
#white="\033[0;37m"        # White
check="\xE2\x9C\x94"      # Check Mark

#---------------------------------
# Gets OS Version.
#---------------------------------
osver=$(lsb_release -ds 2>/dev/null || cat /etc/*release 2>/dev/null | head -n1 || uname -om)

#---------------------------------
# Gets Yum version.
#---------------------------------
YUM_CMD=$(command -v yum)

#---------------------------------
# Gets Apt version.
#---------------------------------
APT_GET_CMD=$(command -v apt-get)

#---------------------------------
# Chronyd service.
#---------------------------------
SERVICE=chronyd;

#---------------------------------
# Currnet kernel version.
#---------------------------------
current=$(uname -r)

#---------------------------------
# Clear the screen.
#---------------------------------
clear 
echo ""

#---------------------------------
# The items needed for validating downloads
#---------------------------------
branch_path=https://raw.githubusercontent.com/B3nd3r15/linuxscripts/master
branch_path_master=https://raw.githubusercontent.com/B3nd3r15/linuxscripts/master
check_download=
updateserver_tmp=/tmp/updateserver.$$
failure_info=
fail_output=
verbose_mode=0

#---------------------------------
# Timestamp function.
#---------------------------------
timestamp()
{
 date +"%Y-%m-%d %T"
}

#---------------------------------
# Check kernel version function.
#---------------------------------
kernelversion(){
#--------------------------------------------------------
# Check kernel version to make sure it is 4.9 or higher.
#--------------------------------------------------------
KERNEL_VERSION=$(uname -r | awk 'BEGIN{ FS="."}; 
    { if ($1 < 4) { print "N"; } 
      else if ($1 == 4) { 
          if ($2 < 9) { print "N"; } 
          else { print "Y"; } 
      } 
      else { print "Y"; }
    }')

if [[ "$KERNEL_VERSION" == 'N' ]]; then
    current=$(uname -r)
    echo "Kernel required version is 4.9 your version is $current"
else
echo "You can enable TCP BBR. Your running kernel version is $current"
echo ""

fi
}

ntpconfig() {
#------------------------------------------------------------------------------------
# The config files for ntp lies in /etc/ntp.conf
# We are changing the Servers time to google's public NTP servers.
# Look here for more info : https://developers.google.com/time/guides#linux_ntpd
#-----------------------------------------------------------------------------------
                echo -e "$yellow" "$check" Modifying NTP config file "$reset"

#-------------------------------------------------
# Comment out the default pool servers.
#-------------------------------------------------
                sed -i 's/pool/#&/' /etc/ntp.conf
                sed -i 's/server/#&/' /etc/ntp.conf

#-------------------------------------------------
# Add the new servers to the end of the file.
#-------------------------------------------------
                sed -i "\$aserver time1.google.com iburst" /etc/ntp.conf
                sed -i "\$aserver time2.google.com iburst" /etc/ntp.conf
                sed -i "\$aserver time3.google.com iburst" /etc/ntp.conf
                sed -i "\$aserver time4.google.com iburst" /etc/ntp.conf
}

#--------------------------------------------------
# This function enables TCP BBR congestion control.
#--------------------------------------------------
tcpbbr(){
#-------------------------------------------------
# Sysctl file to create for config.
#-------------------------------------------------
SYSCTL_FILE=/etc/sysctl.d/10-tcp-bbr.conf

#-------------------------------------------------
# Variable to check for current BBR Status.
#-------------------------------------------------
BBRSTATUS=$(sysctl net.ipv4.tcp_congestion_control | awk '{print $3}')

#---------------------------------
# TCP BBR Config.
#---------------------------------
        echo ""
        echo -e "$blue" "# TCP BBR Started on $osver on $(timestamp) #" "$reset"
        echo ""

#--------------------------------------------------------
# Check kernel version to make sure it is 4.9 or higher.
#--------------------------------------------------------
 KERNEL_VERSION=$(uname -r | awk 'BEGIN{ FS="."}; 
    { if ($1 < 4) { print "N"; } 
      else if ($1 == 4) { 
          if ($2 < 9) { print "N"; } 
          else { print "Y"; } 
      } 
      else { print "Y"; }
    }')

if [[ "$KERNEL_VERSION" == 'N' ]]; then
    current=$(uname -r)
    echo ""
    echo -e "$red" "$check" Kernel required version is 4.9 or higher, your version is $current "$reset"
else
    echo ""
    echo -e "$green" "$check" Your kernel version is greater than 4.9, directly setting TCP BBR! "$reset"

    if ! grep -q "tcp_bbr" "/etc/modules-load.d/modules.conf"; then
        echo "tcp_bbr" >> /etc/modules-load.d/modules.conf | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1
    fi

#-------------------------------------------------
# Display current configuration.
#-------------------------------------------------
    echo ""
    echo -e "$cyan" "$check" Current configuration: "$reset"
    sysctl net.ipv4.tcp_available_congestion_control
    sysctl net.ipv4.tcp_congestion_control

#----------------------------------------------------------------------
# Check BBR Status, if configured don't do anything, if not configure.
#----------------------------------------------------------------------
    if [[ x"${BBRSTATUS}" == x"bbr" ]]; then
        echo ""
        echo -e "$green" "$check" Look at that! BBR is already set up, Go grab a beer! "$reset"
    else

#-------------------------------------------------
# Apply new config.
#-------------------------------------------------
        echo ""
        echo -e "$yellow" "$check" Applying new configuration "$reset"
        #touch $SYSCTL_FILE
        if ! grep -q "net.core.default_qdisc=fq" "$SYSCTL_FILE"; then
            echo "net.core.default_qdisc=fq" >> $SYSCTL_FILE | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1
        fi
        if ! grep -q "net.ipv4.tcp_congestion_control=bbr" "$SYSCTL_FILE"; then
            echo "net.ipv4.tcp_congestion_control=bbr" >> $SYSCTL_FILE | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1
        fi

#-------------------------------------------------
# Check if we can apply the config now.
#-------------------------------------------------
        if lsmod | grep -q "tcp_bbr"; then
            sysctl -p $SYSCTL_FILE | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1
            echo ""
            echo -e "$green" "$check" BBR is available now. "$reset"
        elif modprobe tcp_bbr; then
            sysctl -p $SYSCTL_FILE | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1
            echo -e "$green" "$check" BBR is available now. "$reset"
        else
            echo -e "$red" BBR is not available now, Please reboot to enable BBR. "$reset"
        fi
    fi

fi

#---------------------------------
# End of TCP BBR Config.
#---------------------------------
        echo ""
        echo -e "$blue" "# TCP BBR Complete on $osver on $(timestamp) #" "$reset"
        echo ""
}

#---------------------------------
# Yum Function.
#---------------------------------
yumupdate() {

#---------------------------------
# Update all the things!
#---------------------------------
        echo ""
        echo -e "$blue" "# Upgrading $osver on $(timestamp) #" "$reset"
        echo ""

#---------------------------------
# Clean up unused pacakages.
#---------------------------------
        echo -e "$green" "$check" Cleaning Up Yum Packages "$reset"
        yes | sudo yum clean packages | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1

#---------------------------------
# Clean up Yum Metadata.
#---------------------------------
        echo -e "$green" "$check" Cleaning Up Yum Metadata "$reset"
        yes | sudo yum clean metadata | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1

#---------------------------------
# Clean Yum DB Cache.
#---------------------------------
        echo -e "$green" "$check" Cleaning Up Yum DBCache "$reset"
        yes | sudo yum clean dbcache | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1

#---------------------------------
# Clean anything leftover.
#---------------------------------
        echo -e "$green" "$check" Cleaning up Yum Everything "$reset"
        yes | sudo yum clean all | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1

#---------------------------------
# Remove /var/cache/yum file.
#---------------------------------
        echo -e "$green" "$check" Removing /var/cache/yum "$reset"
        yes | sudo rm -rf /var/cache/yum | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1

#---------------------------------
# Update Yum.
#---------------------------------
        echo ""
        echo -e "$green" "$check" Updating Yum "$reset"
        yes | sudo yum update | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1

#---------------------------------
# Install Updates.
#---------------------------------
        echo -e "$green" "$check" Installing Updates "$reset"
        yes | sudo yum upgrade | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1

#---------------------------------
# End of update section.
#---------------------------------
        echo ""
        echo -e "$blue" "# End of Upgrade on $(timestamp) #" "$reset"
        echo ""

#----------------------------------
# Start disable of Chronyd Service.
#----------------------------------
        if P=$(pgrep $SERVICE); then
                 echo -e "$red" "$SERVICE" is running, PID is "$P", Disabling chronyd service. "$reset"
                # Stop the Chronyd Service
                systemctl stop chronyd
                # Disable chronyd so it cannot start if server reboots.
                systemctl disable chronyd
        else
                echo -e "$green" "$check" "$SERVICE" is not running or has been disabled. "$reset"
        fi

#--------------------------------------------------------------------------------------
# Checks to see if NTP is installed. If it is, continues to check if the config file
# is modified if not it will install it and update the config file.
#-------------------------------------------------------------------------------------
        if yum list installed | grep ntp.x86_64 > /dev/null 2>&1; then
                echo ""
                echo -e "$green" "$check" NTP Successfully Installed "$reset"
        else
                echo -e "$yellow" "$check" Installing NTP "$reset"
                yes | sudo yum install ntp ntpd | sudo tee -a $LOG_LOCATION/"${scriptname}".log
        fi

#-------------------------------------------------
# Checks to see if the config files need updated.
#-------------------------------------------------
        if grep google.com /etc/ntp.conf > /dev/null 2>&1; then
                echo -e "$green" "$check" NTP conf file already updated. "$reset"
        else
                ntpconfig

#-----------------------------------------------------
# Restart, enable, and show the status of the service.
#-----------------------------------------------------
                echo -e "$green" "$check" Restarting NTP Service "$reset"
                sudo systemctl stop ntpd
                sleep 2
                sudo systemctl start ntpd
                sleep 2
                sudo systemctl enable ntpd
                sleep 2
                sudo systemctl status ntpd

#-----------------------------------------------------------------
# Give ntp service time to start up and talk to time*.google.com.
#-----------------------------------------------------------------
        echo -e "$yellow" "$check" Waiting for NTP service to start "$reset"
        sleep 5

        fi
#-------------------------------------------------
# Show NTP servers.
#-------------------------------------------------
        echo -e "$green" "$check" Showing current NTP Servers "$reset"
        echo ""
        ntpq -p
        echo ""
        ntpstat
        echo ""
}

#---------------------------------
# Apt Function.
#---------------------------------
aptupdate() {

#---------------------------------
# Update all the things!
#---------------------------------
        echo ""
        echo -e "$blue" "# Upgrading $osver on $(timestamp) #" "$reset"
        echo ""

#---------------------------------
# Remove old software.
#---------------------------------
        echo -e "$green" "$check" Removing Unused Software "$reset"
        yes|sudo apt-get autoremove | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1

#---------------------------------
# Purge config files.
#---------------------------------
        echo -e "$green" "$check" Purging Leftover Config Files "$reset"
        #sudo dpkg --purge $(COLUMNS=200 dpkg -l | grep "^rc" | tr -s ' ' | cut -d ' ' -f 2) | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1
        sudo apt-get purge -y "$(dpkg -l | awk '/^rc/ { print $2 }')" | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1

#---------------------------------
# Update all the repos.
#---------------------------------
        echo -e "$green" "$check" Updating Repos "$reset"
        yes | sudo apt-get update | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1

#---------------------------------
# Upgrade all the things.
#---------------------------------
        echo -e "$green" "$check" Upgrading System "$reset"
        yes | sudo apt-get dist-upgrade | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1

#---------------------------------
# End of update section.
#---------------------------------
        echo ""
        echo -e "$blue" "# End of Upgrade on $(timestamp) #" "$reset"
        echo ""

#---------------------------------
# Ask user if they would like
# to check for new LTS release.
#---------------------------------
        if do-release-upgrade -c >> /dev/null; then
                echo ""
                read -r -t 10 -p "Would you like to install the new LTS release?  " -e -i 'N' input
                yesno=${input:-n}
                echo ""
        case $yesno in
                [Yy]* ) do-release-upgrade;;
                [Nn]* ) echo -e "$yellow" "Skipping Upgrade" "$reset";;
                * ) echo -e "$yellow" "Invalid option, Skipping Upgrade" "$reset";;
                esac
        else
                echo ""
                echo -e "$green" "No new LTS release available or no action taken." "$reset"
        fi

#----------------------------------------------
# Checks to see if NTP is installed.
# If it is, continues to modify config file,
# if not it will install it.
#----------------------------------------------

        if apt-get -qq install ntp ntpstat; then
                echo ""
                echo -e "$green" "$check" "NTP Successfully Installed" "$reset"
        else
                echo ""
                echo -e "$yellow" "Installing NTP" "$reset"
                yes | sudo apt-get install ntp ntpstat | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1
        fi

#---------------------------------
# Checks to see if the config files need updated.
#---------------------------------
        if grep google.com /etc/ntp.conf > /dev/null 2>&1; then
                echo -e "$green" "$check" NTP config file already updated. "$reset"
        else
                ntpconfig
        fi

#---------------------------------
# Restart the NTP service.
#---------------------------------
                echo ""
                echo -e "$green" "$check" Restarting NTP Service "$reset"
                echo ""
                sudo systemctl stop ntp
                sleep 2
                sudo systemctl start ntp
                sleep 2
                sudo systemctl enable ntp
                sleep 2
                sudo systemctl status ntp

#----------------------------------------------------------------
# Give ntp service time to start up and talk to time*.google.com.
#----------------------------------------------------------------
                echo ""
                echo -e "$yellow" "$check" Waiting for NTP service to start "$reset"
                sleep 5

#---------------------------------
# Show NTP servers.
#---------------------------------
        echo -e "$green" "$check" "Showing current NTP Servers" "$reset"
        echo ""
        ntpq -p
        echo ""
        ntpstat
        echo ""

}

autoupdate(){

# The items needed for validating downloads
branch_path=https://raw.githubusercontent.com/B3nd3r15/linuxscripts/master
branch_path_master=https://raw.githubusercontent.com/B3nd3r15/linuxscripts/master
check_download=
updateserver_tmp=/tmp/updateserver.$$
failure_info=
fail_output=
verbose_mode=0


echo -e "$yellow" "$check" "# Updating Myself on $(timestamp) #" "$reset"
echo ""
curl -j "$branch_path/updateserver" -o "$updateserver_tmp"; grep -q version "$updateserver_tmp"; check_download=$(echo $?);
    if [ "$check_download" -eq "1" ]; then
        # Branch path must be wrong or a bad curl occurred, try against our master repo 
        curl -j "$branch_path_master/updateserver" -o "$updateserver_tmp"; grep -q version "$updateserver_tmp"; check_download=$(echo $?) ;
        if [ "$check_download" -eq "1" ]; then
            # We tried twice to get the script but failed, time to bail out
            CLEAN_UP
            exit 0
        else
            fail_output="${fail_output}1"
        fi
    else
        fail_output="${fail_output}0"
    fi

# If we made it here, it means that we successfully downloaded all the scripts.
    mv "$updateserver_tmp" /usr/bin/updateserver; chmod +x /usr/bin/updateserver | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1
    echo ""
    echo -e "$green" "$check" "# Update Complete on $(timestamp) #" "$reset"
    echo ""
#    [[ ${verboseverbose_mode} -eq "1" ]] && echo "COMMANDLINE: ${commandline}"
#    if [ -z "$commandline" ]
#    then
#    exec env /bin/sh "$0" "-s" "-second_pass" "-fail_output" "$fail_output"
#    else
#    exec env /bin/sh "$0" "${commandline}" "-s" "-second_pass" "-fail_output" "$fail_output"
#    fi
#    exit 0

}

automatic(){
#--------------------------------------------------
# Determine Installed packaging system.
#--------------------------------------------------
if [[ -n $YUM_CMD ]]; then
        autoupdate
        yumupdate
        tcpbbr
        cleanup

        echo ""
        echo -e "$cyan" To view the log file: [ less $LOG_LOCATION/"${scriptname}".log ] "$reset"
        echo ""

elif [[ -n $APT_GET_CMD ]]; then
        autoupdate
        aptupdate
        tcpbbr
        cleanup

        echo ""
        echo -e "$cyan" To view the log file: [ less $LOG_LOCATION/"${scriptname}".log ] "$reset"
        echo ""

#-----------------------------------------------------------------------------------------------------
# If neither Yum or Apt are installed, exit and have user manually install updates on their system.
#-----------------------------------------------------------------------------------------------------
else
        echo "Cannot determine installed packaging system, Please manually update."
        exit 1;
fi
}

# Anything that needs to be removed at the end of the program needs to be here
cleanup () {
#[[ -e "$combined_uptime" ]] && rm "$combined_uptime"
[[ -e "$updateserver_tmp" ]] && rm "$updateserver_tmp" | sudo tee -a $LOG_LOCATION/"${scriptname}".log >> /dev/null 2>&1
}

# The "$@" that follows this line is intentional and exists to allow you to call functions within the script from a command line.
"$@"